#!/usr/bin/env python3
"""
Flower Client for Federated NIDS
Wraps the NIDS and participates in federated learning
"""

import numpy as np
from typing import List, Dict, Tuple, Optional
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core import ClosedLoopNIDS


class FederatedClient:
    """Flower-compatible federated client"""
    
    def __init__(self, client_id: str, traffic_pattern: str = "normal"):
        self.cid = client_id
        self.pattern = traffic_pattern
        self.nids = ClosedLoopNIDS()
        self.round_count = 0
        
        print(f"[{client_id}] Initialized with pattern: {traffic_pattern}")
    
    def get_parameters(self) -> List[np.ndarray]:
        """Get NIDS parameters for federation"""
        # Extract key parameters as arrays
        params = [
            np.array([0.5], dtype=np.float32),  # threshold
            np.array([5.0, 3.0], dtype=np.float32),  # packet_rate baseline
            np.array([3.0, 2.0], dtype=np.float32),  # port_diversity baseline
            np.array([2.0, 2.0], dtype=np.float32),  # connection_rate baseline
        ]
        return params
    
    def set_parameters(self, params: List[np.ndarray]) -> None:
        """Apply federated parameters to NIDS"""
        if params:
            print(f"[{self.cid}] Received {len(params)} parameter arrays")
    
    def fit(self, parameters: List[np.ndarray], config: Dict) -> Tuple:
        """Process packets and generate rules (federated learning fit)"""
        self.round_count += 1
        round_num = config.get('round_number', self.round_count)
        
        # Apply global parameters
        self.set_parameters(parameters)
        
        # Generate traffic and process
        packets = self._generate_traffic(100)
        anomalies = 0
        rules_generated = 0
        
        for pkt in packets:
            anomaly = self.nids.process_packet(pkt)
            if anomaly:
                anomalies += 1
                rules_generated += 1
        
        # Get updated parameters
        new_params = self.get_parameters()
        
        metrics = {
            'loss': 1.0 - (anomalies / max(len(packets), 1)),
            'anomalies_detected': anomalies,
            'rules_generated': rules_generated,
            'packets_processed': len(packets),
        }
        
        print(f"[{self.cid}] Round {round_num}: {anomalies} anomalies, {rules_generated} rules")
        
        return new_params, len(packets), metrics
    
    def _generate_traffic(self, num_packets: int) -> List[Dict]:
        """Generate simulated traffic based on pattern"""
        packets = []
        
        if self.pattern == "port_scan":
            for i in range(num_packets):
                packets.append({
                    'src': '192.168.1.100', 'dst': '10.0.0.1',
                    'proto': 'tcp', 'dport': i % 100 + 1, 'flags': 'S', 'length': 64
                })
        elif self.pattern == "syn_flood":
            for i in range(num_packets):
                packets.append({
                    'src': f'192.168.1.{200 + (i % 3)}', 'dst': '10.0.0.2',
                    'proto': 'tcp', 'dport': 80, 'flags': 'S', 'length': 64
                })
        elif self.pattern == "normal":
            for i in range(num_packets):
                packets.append({
                    'src': f'192.168.1.{10 + (i % 5)}', 'dst': '10.0.0.10',
                    'proto': 'tcp', 'dport': [80, 443, 22][i % 3],
                    'flags': 'PA', 'length': 500 + (i % 100)
                })
        else:  # mixed
            normal = int(num_packets * 0.7)
            for i in range(normal):
                packets.append({'src': '192.168.1.10', 'dst': '10.0.0.10',
                              'proto': 'tcp', 'dport': 80, 'flags': 'PA', 'length': 500})
            for i in range(num_packets - normal):
                packets.append({'src': '192.168.1.100', 'dst': '10.0.0.10',
                              'proto': 'tcp', 'dport': i + 1, 'flags': 'S', 'length': 64})
        
        return packets
    
    def get_local_rules(self) -> List[Dict]:
        """Get rules generated by this client"""
        return self.nids.rule_generator.get_rules_dict()
